// Generated by `pnpm abi:sync` from smart-contract@c36fd6e678ff727da4aaf3b4b3e47a063dcaa898. Do not edit.
// Events only: the indexer decodes logs and never calls contracts.
export const collateralPolicyAbi = [
  {
    "type": "event",
    "name": "HookAllowlisted",
    "inputs": [
      {
        "name": "hooks",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "allowed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LtRampScheduled",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "ltFromBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "ltTargetBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "start",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      },
      {
        "name": "duration",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PoolFrozen",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "frozen",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PoolListed",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "tier",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum ICollateralPolicy.Tier"
      },
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct CollateralPolicy.ListingParams",
        "components": [
          {
            "name": "maxLtvBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidatorBonusBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "removeHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "debtCapUsdg",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minPositionUsd",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PoolTermsUpdated",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct CollateralPolicy.ListingParams",
        "components": [
          {
            "name": "maxLtvBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "ltBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "liquidatorBonusBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "removeHaircutBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "debtCapUsdg",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "minPositionUsd",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenConfigured",
    "inputs": [
      {
        "name": "currency",
        "type": "address",
        "indexed": true,
        "internalType": "Currency"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "tier",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum ICollateralPolicy.Tier"
      },
      {
        "name": "decimals",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      },
      {
        "name": "priceFeed",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;
