// Generated by `pnpm abi:sync` from smart-contract@21dc839c85ff049f16521062facdddb7aceede89. Do not edit.
// Events only: the indexer decodes logs and never calls contracts.
export const twapRecorderAbi = [
  {
    "type": "event",
    "name": "Recorded",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "index",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "timestamp",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "tickCumulative",
        "type": "int56",
        "indexed": false,
        "internalType": "int56"
      }
    ],
    "anonymous": false
  }
] as const;
