// Regenerates abis/*.ts from the smart-contract commit pinned in abis/source.json.
//
//   pnpm abi:sync               rebuild from the pinned commit
//   pnpm abi:sync --pin <sha>   move the pin to <sha> (full 40-char sha), then rebuild
//
// By default the pinned commit is cloned into .cache/smart-contract. To reuse a checkout
// that already has its submodules, set SMART_CONTRACT_DIR; it must sit exactly on the
// pinned commit with a clean tree, otherwise the ABIs would not be the ones the pin names.
//
// Requires git and forge (Foundry) on PATH.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_FILE = join(ROOT, "abis/source.json");

// Output file -> forge artifacts it is assembled from. The indexer only decodes logs
// (spec §13: it never calls contracts), so only `event` entries are kept.
// PositionManager is two artifacts because IPositionManager does not inherit the ERC-721
// interface that declares `Transfer`.
const TARGETS = {
  FarmentaMarket: ["FarmentaMarket.sol/FarmentaMarket.json"],
  CollateralPolicy: ["CollateralPolicy.sol/CollateralPolicy.json"],
  TwapRecorder: ["TwapRecorder.sol/TwapRecorder.json"],
  PoolManager: ["IPoolManager.sol/IPoolManager.json"],
  PositionManager: ["IPositionManager.sol/IPositionManager.json", "IERC721.sol/IERC721.json"],
};

function run(cmd, args, cwd) {
  return execFileSync(cmd, args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] }).trim();
}

function fail(message) {
  console.error(`abi:sync: ${message}`);
  process.exit(1);
}

const source = JSON.parse(readFileSync(SOURCE_FILE, "utf8"));

const pinIndex = process.argv.indexOf("--pin");
if (pinIndex !== -1) {
  const sha = process.argv[pinIndex + 1];
  if (!/^[0-9a-f]{40}$/.test(sha ?? "")) fail("--pin takes a full 40-character commit sha");
  source.commit = sha;
}

function prepareCheckout() {
  const external = process.env.SMART_CONTRACT_DIR;
  if (external) {
    const dir = resolve(ROOT, external);
    const head = run("git", ["rev-parse", "HEAD"], dir);
    if (head !== source.commit) fail(`${dir} is at ${head}, but the pin is ${source.commit}`);
    if (run("git", ["status", "--porcelain"], dir) !== "") fail(`${dir} has uncommitted changes`);
    return dir;
  }

  const dir = join(ROOT, ".cache/smart-contract");
  if (!existsSync(dir)) {
    mkdirSync(dirname(dir), { recursive: true });
    run("git", ["clone", "--no-checkout", source.repo, dir], ROOT);
  }
  run("git", ["fetch", "origin"], dir);
  run("git", ["checkout", "--detach", "--force", source.commit], dir);
  run("git", ["submodule", "update", "--init", "--depth", "1"], dir);
  // Not --recursive: that also pulls each library's own test dependencies, which is most
  // of the download. The nested submodules the build needs are exactly the ones
  // remappings.txt points into (lib/<a>/lib/<b>/).
  const nested = new Set();
  for (const line of readFileSync(join(dir, "remappings.txt"), "utf8").split("\n")) {
    const match = line.match(/=(lib\/[^/]+)\/(lib\/[^/]+)\//);
    if (match) nested.add(`${match[1]} ${match[2]}`);
  }
  for (const entry of nested) {
    const [parent, child] = entry.split(" ");
    run("git", ["submodule", "update", "--init", "--depth", "1", child], join(dir, parent));
  }
  return dir;
}

const checkout = prepareCheckout();
console.log(`abi:sync: building ${source.commit} in ${checkout}`);
run("forge", ["build", "--skip", "test", "--skip", "script"], checkout);

// Two artifacts may declare the same event; keep one copy per signature.
function signature(event) {
  const types = (inputs) =>
    inputs.map((input) => (input.type.startsWith("tuple") ? `(${types(input.components)})${input.type.slice(5)}` : input.type));
  return `${event.name}(${types(event.inputs).join(",")})`;
}

for (const [name, artifacts] of Object.entries(TARGETS)) {
  const events = new Map();
  for (const artifact of artifacts) {
    const { abi } = JSON.parse(readFileSync(join(checkout, "out", artifact), "utf8"));
    for (const entry of abi) {
      if (entry.type === "event") events.set(signature(entry), entry);
    }
  }
  const sorted = [...events.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, event]) => event);
  const constName = `${name[0].toLowerCase()}${name.slice(1)}Abi`;
  const body =
    `// Generated by \`pnpm abi:sync\` from smart-contract@${source.commit}. Do not edit.\n` +
    `// Events only: the indexer decodes logs and never calls contracts.\n` +
    `export const ${constName} = ${JSON.stringify(sorted, null, 2)} as const;\n`;
  writeFileSync(join(ROOT, `abis/${name}.ts`), body);
  console.log(`abi:sync: abis/${name}.ts (${sorted.length} events)`);
}

writeFileSync(SOURCE_FILE, `${JSON.stringify(source, null, 2)}\n`);
